// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAd9jmpS-yU8oZn4lpfzag_SIXLcPNkII',
    appId: '1:477546501319:web:a9ba1eda8e7b04c7ad1ae2',
    messagingSenderId: '477546501319',
    projectId: 'flutter-chat-app-18edd',
    authDomain: 'flutter-chat-app-18edd.firebaseapp.com',
    storageBucket: 'flutter-chat-app-18edd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqJuQIYDhd3W_WOOjtrwEYrJN58G-Lhzo',
    appId: '1:477546501319:android:4e277938b7bd31cead1ae2',
    messagingSenderId: '477546501319',
    projectId: 'flutter-chat-app-18edd',
    storageBucket: 'flutter-chat-app-18edd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdiIMBuTaBOJULQs_ZgFZJ10kjRvRYr9I',
    appId: '1:477546501319:ios:93fc8ec635316da3ad1ae2',
    messagingSenderId: '477546501319',
    projectId: 'flutter-chat-app-18edd',
    storageBucket: 'flutter-chat-app-18edd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdiIMBuTaBOJULQs_ZgFZJ10kjRvRYr9I',
    appId: '1:477546501319:ios:93fc8ec635316da3ad1ae2',
    messagingSenderId: '477546501319',
    projectId: 'flutter-chat-app-18edd',
    storageBucket: 'flutter-chat-app-18edd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAd9jmpS-yU8oZn4lpfzag_SIXLcPNkII',
    appId: '1:477546501319:web:a25cfc1a18dd0dcaad1ae2',
    messagingSenderId: '477546501319',
    projectId: 'flutter-chat-app-18edd',
    authDomain: 'flutter-chat-app-18edd.firebaseapp.com',
    storageBucket: 'flutter-chat-app-18edd.appspot.com',
  );

}